#!/bin/env bash

if [ "$1" ]; then
	dia=$1
else
	dia=$(date +%d)
fi

if [ "$2" ]; then
	mes=$(($2 + 1))
else
	mes=$(date +%m)
fi

if [ "$3" ]; then
	ano=$3
else
	ano=$(date +%Y)
fi

eww update mesano="$(date -d "${ano}-${mes}-${dia}" '+%B %Y')"

eventos=$(khal list "${dia}/${mes}/${ano}" eod --format '{{ "name": "{title}", "start": "{start-long}", "end": "{end-long}", "location": "{location}", "calendar": "{calendar}" }}' | tail -n +2 | jq -cs)
# .[].start |= (strptime("%d/%m/%Y %H:%M")|mktime) | .[].end |= (strptime("%d/%m/%Y %H:%M")|mktime)

todo=$(todo --porcelain | jq -c)

date="$(date -d "${ano}-${mes}-${dia}" '+%s')"

echo "{ \"events\": ${eventos}, \"todo\": ${todo}, \"date\": ${date} }"
