#!/bin/zsh
#
alias sudo='sudo '

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv" \
	rsync="rsync -vh --progress" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

alias \
	ka="killall" \
	g="git" \
	f="$EXPLORER" \
	e="$EDITOR" \
	\#="sudo"

alias ll='ls -lhA --color=auto --group-directories-first'
alias  l='ls -lh  --color=auto --group-directories-first'
alias r2mod="io.github.Foldex.r2mod"
alias scrape="curl -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:113.0) Gecko/20100101 Firefox/113.0'"

alias arduino-cli="arduino-cli --config-file ${XDG_CONFIG_HOME}/arduino-cli/arduino-cli.yaml"
alias static_file_server="python -m http.server 8000"
alias paste_image="xclip -selection clpboard -t image/png -o"

alias nsxiv="nsxiv ${XEMBED+"-e $XEMBED"}"
alias mpv="mpv ${XEMBED+"--wid=$XEMBED"}"
alias zathura="zathura ${XEMBED+"-e $XEMBED"}"
alias surf="surf ${XEMBED+"-e $XEMBED"}"
alias gpp="g++"

converter265 () {
	if [ "${HOSTNAME}" = "vivobook" ]; then
		addy="by-path/pci-0000:$(lspci | grep -i 'uhd graphics' | awk '{print $1}')-render"
	else
		addy="renderD128"
	fi

	if [ $2 ]; then
		dest="$2" 
	else
		dest="./x265/${1%.*}.mkv"
		[ -d x265 ] || mkdir x265
	fi

  echo $dest
  ffmpeg \
		-vaapi_device "/dev/dri/${addy}" \
		-hwaccel vaapi \
		-hwaccel_output_format vaapi \
		-i "$1" \
		-vf 'format=nv12|vaapi,hwupload' \
		-threads 8 \
		-vcodec hevc_vaapi \
		-acodec copy \
		-rc_mode CQP \
		-profile:v main \
		-v verbose "${dest}"
}

converter265todos () {
   for myvid in *
   do
		converter265 $myvid
   done
}

precmd() {
   if [ "$?" != 0 ]; then
   	 (paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga &)
   fi
}

stderr() { printf "%s\n" "$*" >&2; }

rules() {
	xprop | awk '
	/^WM_CLASS/{sub(/.* =/, "instance:"); sub(/,/, "\nclass:"); print}
	/^WM_NAME/{sub(/.* =/, "title:"); print}'
}

ip_camera() {
	ffmpeg -i http://"$1"/video -vf format=yuv420p -f v4l2 /dev/video0
}

# whisper () {
# 	index="$1"
# 	duration=900000
# 	((result = index * duration))
# 	# printf "%s\n\n\n" "${result}"
# 	./build/bin/whisper-cli -m /home/mamba/Downloads/whisper.cpp/models/ggml-large-v3.bin -l pt -ot "${result}" -d "${duration}" -f ~/Downloads/output2.wav
# }
